### ISSUE TITLE
Break primary build into physical stages

### ISSUE THREAD

**Issue by mike-ensor** [GoogleCloudPlatform/solutions-modern-cicd-anthos#27]
The current build implements one large cloud build process.  Failures in late stages of the build require a full destroy and rebuild due to stage 4+ not being idempotent.

This issue/story will use a parent/child job structure and in conjunction with remote state to break up the build into modules or stages.

The final solution will need to have a one-click/one-command to "build it all", but will allow each segment to be destroyed and rebuilt independently so a failure in late stage can be build independently without requiring a 30-45 minute destroy/rebuild.

**Comment by viglesiasce** [comment]
Nice!!! looking forward to this.

**Comment by mike-ensor** [comment]
Proposed solution:

The process will identify build stages with explicit qualifications for completion (ie, Cluster stage, currently 1_clusters, will have clusters of X size, Y enabled features/addons, etc).  The destroy will be moved to the stages to pair with the builds.

The master build will run all of the stages in sequence, but will delegate building to scripts in each stage, as well as the complementary destroy scripts.

Optionally (possibly future?) we can add in flags or a configuration to change the build stage process (like only build up to ASM complete, or build to Services install and only install X app)

**Comment by mike-ensor** [comment]
Code merged with #47
