### ISSUE TITLE
Destroy path takes out existing clusters

### ISSUE THREAD

**Issue by viglesiasce** [GoogleCloudPlatform/solutions-modern-cicd-anthos#42]
I got a report from a user that they used our setup and the destroy step took out their non-related clusters.

We should tag our clusters and use those tags to filter out the ones we want to destroy.

**Comment by viglesiasce** [comment]
@bgood can you take a look.

**Comment by bgood** [comment]
Yes, we will try to make the destroy script more targeted.

**Comment by morgante** [comment]
Have we considered switching to using `terraform destroy`? It would do a better job of picking up these cases and hopefully require less maintenance.

**Comment by viglesiasce** [comment]
We started there but hit lots of issues due to the Helm release destruction
conflicting with cluster teardown. Would love to get back to that if we can
make it work.

**Comment by morgante** [comment]
We might be able to work around that by doing a more targeted destroy (ie don't try to destroy the Helm release).

**Comment by viglesiasce** [comment]
Awesome! I was trying to figure out how to do that and gave up.

**Comment by mike-ensor** [comment]
#27 should help address this concern as well.  The process will identify build stages with explicit qualifications for completion (ie, Cluster stage, currently 1_clusters, will have clusters of X size, Y enabled features/addons, etc).  The destroy will be moved to the stages to pair with the builds.

The master build will run all of the stages in sequence, but will delegate to the builds for that stage, as well as the destroys

**Comment by viglesiasce** [comment]
This should be fixed in #47

**Comment by mike-ensor** [comment]
Destroy now only uses Terraform to back out IaC
