### ISSUE TITLE
Unable to add new app with anthos-platform-cli

### ISSUE THREAD

**Issue by romankhar** [GoogleCloudPlatform/solutions-modern-cicd-anthos#53]
This worked for me a week ago on a different project. Now recreated the entire environment and not able to add new application using the command 
```
anthos-platform-cli add app \
    --name $APP_NAME \
    --gitlab-hostname $GITLAB_HOSTNAME \
    --gitlab-token $GITLAB_ROOT_PASSWORD \
    --template-name golang-template
  
```

Here is the error I am getting:

```
INFO[0001] Creating AR repository test-app-1 in location us-central1
INFO[0004] Creating service account test-app-1-push
FATA[0006] Unable to add binding for service account test-app-1-push@Your active configuration is: [cicd-anthos]
kharkovski-anthos-cicd.iam.gserviceaccount.com: ERROR: Policy modification failed. For a binding with condition, run "gcloud alpha iam policies lint-condition" to identify issues in condition.
ERROR: (gcloud.beta.artifacts.repositories.add-iam-policy-binding) INVALID_ARGUMENT: Invalid service account (test-app-1-push@Your active configuration is: [cicd-anthos]
kharkovski-anthos-cicd.iam.gserviceaccount.com).
```

I checked and the IAM service account was created as well as the artifact registry in GCP. Also it seems to me that the name of the Service Account is somehow broken.

**Comment by henrybell** [comment]
Hi Roman -- I've reached out via email so that we can understand what's happening in your environment. Thanks!

**Comment by henrybell** [comment]
We currently link to an older version of the CLI (0.6.1) in the documentation -- this old version does not include the fix to support the use of multiple `gcloud config configurations`. This can result in spurious extra output breaking the embedded use of the `gcloud` command in the CLI as was happening in this case. Created #54 to track the automated CLI build and release process. Thanks @romankhar for raising this.

**Comment by romanseibel** [comment]
Just stumbled on the same issue.

To clarify the workaround is to build the anthos-platform-cli from the repo code and use it instead of downloading from https://storage.googleapis.com/solutions-public-assets/anthos-platform-cli/v0.6.1/anthos-platform-cli-v0.6.1-linux-amd64

To build the cli in Cloud Shell and deploy the sample golang app:
```
cd cli
make release
./release/anthos-platform-cli-vlatest-linux-amd64 add app --name $APP_NAME --gitlab-hostname $GITLAB_HOSTNAME --gitlab-token $GITLAB_TOKEN --template-name golang-template
```
