### ISSUE TITLE
Cloud Endpoints and managed certs for Gitlab

### ISSUE THREAD

**Issue by bgood** [GoogleCloudPlatform/solutions-modern-cicd-anthos#62]
Currently users need to bring their own domain and certificates when deploying the solution.  We could use Cloud Endpoints and Google managed certs to make it easier.

**Comment by henrybell** [comment]
Fixed by moving to Cloud Endpoints for DNS (though still certmanager for certificates) via https://github.com/GoogleCloudPlatform/solutions-modern-cicd-anthos/pull/72.
